version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # or your subdirectory if different
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@angular/*"
        versions: ["20.x"]
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "@angular/*"
        versions: [">=21.0.0"]
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
